In [1]:
import numpy as np

In [2]:
import random

In [3]:
# Задание 1
nums = np.arange(10, 0, -1)
nums

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
# Задание 2
x = np.diag(np.arange(56, 0, -12),k=0)
x

array([[56,  0,  0,  0,  0],
       [ 0, 44,  0,  0,  0],
       [ 0,  0, 32,  0,  0],
       [ 0,  0,  0, 20,  0],
       [ 0,  0,  0,  0,  8]])

In [75]:
x.sum()

128

In [77]:
from numpy import linalg

In [81]:
# Задание 3
"""Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3"""

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [85]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [3]:
# Задание 4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [32]:
# Максимально похожий пользователь users_stats на next_user_stats номер 8
resalt = []
for user in users_stats:
    a = np.array(user)
    b = np.array(next_user_stats)
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    resalt.append(np.dot( a, b ) / ( aLength * bLength ))
    print(resalt[-1])

0.19999999999999996
0.8451542547285165
0.3999999999999999
0.7905694150420948
0.3999999999999999
0.0
0.0
0.9486832980505138
0.0
0.0
